// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parks.Models;

namespace Parks.Migrations
{
    [DbContext(typeof(ParksContext))]
    partial class ParksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Parks.Models.NationalPark", b =>
                {
                    b.Property<int>("NationalParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("State");

                    b.HasKey("NationalParkId");

                    b.ToTable("NationalParks");

                    b.HasData(
                        new
                        {
                            NationalParkId = 1,
                            Description = "Weird-looking trees",
                            Name = "Joshua Tree NP",
                            State = "CA"
                        },
                        new
                        {
                            NationalParkId = 2,
                            Description = "Weird-looking rocks",
                            Name = "Arches NP",
                            State = "UT"
                        },
                        new
                        {
                            NationalParkId = 3,
                            Description = "Weird-looking Gators",
                            Name = "Everglades NP",
                            State = "FL"
                        });
                });

            modelBuilder.Entity("Parks.Models.StatePark", b =>
                {
                    b.Property<int>("StateParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.HasKey("StateParkId");

                    b.ToTable("StateParks");

                    b.HasData(
                        new
                        {
                            StateParkId = 1,
                            Description = "Weird-looking trees",
                            Location = "IN",
                            Name = "Turkey Run SP"
                        },
                        new
                        {
                            StateParkId = 2,
                            Description = "Weird-looking lizards",
                            Location = "UT",
                            Name = "Snow Canyon SP"
                        },
                        new
                        {
                            StateParkId = 3,
                            Description = "Weird-looking plants",
                            Location = "NV",
                            Name = "Valley of Fire SP"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
